### ISSUE TITLE
allow Start to be public so it can be set back to 0 for non-CLU usage

### ISSUE THREAD

**Issue by elv-todd** [eluv-io/log-go#5]
so, I notice that "text" format logs use timestamps in the entries, eg,
```
2022-12-20T01:22:51.423Z INFO  DoNotify                  logger=/eluvio/pushservice userId=0x3C48a30Fc0085E63dB0D88d46551435B7ba5fD37 tenantId=itenYQbgk66W1BFEqWr95xPmHZEjmdF type=LISTING_SOLD doPush=true
```
but "console" format gets offsets:
```
95.333     DoNotify       userId=0x3c48a30fc0085e63db0d88d46551435b7ba5fd37 tenantId=itenYQbgk66W1BFEqWr95xPmHZEjmdF type=TOKEN_UPDATED doPush=true
```
this happens due to start getting set to Now:
```
// New creates a new console handler.
func New(w io.Writer) *Handler {
   return &Handler{
      start:  utc.Now(),
      Writer: w,
   }
}
```

I hear this is for CLI.  let's make a PR to change `start` to public `Start` so people can change it after, not have to give up on color.  don't want to give up color..

**Comment by elv-todd** [comment]
@lukseven @elv-john told me you own this guy -- can i get permission to push a PR here?  need perms

**Comment by lukseven** [comment]
> @lukseven @elv-john told me you own this guy -- can i get permission to push a PR here? need perms

done
